[versions]
minecraft = "1.21.11"
fabric-loader = "0.18.2"
carpet = "1.21.11-1.4.193+v251211"
commons-compress = "1.28.0"
bigmath = "2.3.2"

[libraries]
minecraft-fabric = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
carpet-fabric = { module = "carpet:fabric-carpet", version.ref = "carpet" }
apache-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
bigmath = { module = "ch.obermuhlner:big-math", version.ref = "bigmath" }

[plugins]
fabricloom = { id = "fabric-loom", version = "1.14-SNAPSHOT" }
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }
modpublishplugin = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }
